### ISSUE TITLE
Usa removeEventListener

### ISSUE THREAD

**Issue by lmagarin** [pxblx/ticTacToe#3]
https://github.com/pxblx/ticTacToe/blob/5f713fa8521e0bde9a81342c64afe4851352dde6/js/main.js#L21

**Comment by pxblx** [comment]
En lugar de usar removeEventListener, al hacer clic en una celda le añado la clase "desactivada", que incluye la propiedad "pointer-events: none" para desactivar los clicks y el efecto del hover.

**Comment by lmagarin** [comment]
Ya lo sé, pero es que TODO lo solucionas con las clases... Todo lo pasas al css en todos tus diseños. Parece como si no supieras modificar el comportamiento aparte de las clases

**Comment by pxblx** [comment]
Pero ahora el listener lo tiene el document...

**Comment by lmagarin** [comment]
Tienes razón. POR AHÍ te vas a escapar.
😜
